import jsPDF from 'jspdf';

export const generateCSRCertificate = (funding, proposal, issue) => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('CSR Compliance Certificate', 105, 20, { align: 'center' });

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text('Community Hero — Societal Innovation Collaboration Portal', 105, 28, { align: 'center' });

    doc.line(20, 34, 190, 34);

    let y = 45;
    const addRow = (label, value) => {
        doc.setFont(undefined, 'bold');
        doc.text(label, 20, y);
        doc.setFont(undefined, 'normal');
        doc.text(String(value || 'N/A'), 80, y);
        y += 10;
    };

    addRow('Certificate ID:', funding.id || 'PENDING');
    addRow('Company:', funding.companyEmail);
    addRow('Amount Funded:', `Rs. ${String(funding.amount || 'N/A').replace(/[₹]/g, '').trim()}`);
    addRow('Date:', new Date().toLocaleDateString('en-IN'));
    addRow('Implementing Partner:', proposal.uniEmail);
    addRow('Project Category:', issue?.aiCategory || 'N/A');
    addRow('Location:', issue?.location || 'N/A');

    y += 5;
    doc.setFont(undefined, 'bold');
    doc.text('Project Description:', 20, y);
    y += 8;
    doc.setFont(undefined, 'normal');
    const descLines = doc.splitTextToSize(issue?.description || 'N/A', 170);
    doc.text(descLines, 20, y);
    y += descLines.length * 6 + 6;

    doc.setFont(undefined, 'bold');
    doc.text('Proposed Solution:', 20, y);
    y += 8;
    doc.setFont(undefined, 'normal');
    const solLines = doc.splitTextToSize(proposal.solution || 'N/A', 170);
    doc.text(solLines, 20, y);
    y += solLines.length * 6 + 10;

    doc.line(20, y, 190, y);
    y += 8;
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
        'This certificate is auto-generated by the Community Hero platform as a record of CSR fund allocation under the Societal Innovation Collaboration Portal (PS26043).',
        20, y, { maxWidth: 170 }
    );

    doc.save(`CSR-Certificate-${funding.id || Date.now()}.pdf`);
};