import jsPDF from 'jspdf';

export const generateCSRCertificate = (funding, proposal, issue) => {
  const doc = new jsPDF();
  const pageWidth = 210;
  const margin = 15;

  // Outer decorative border
  doc.setDrawColor(20, 40, 90);
  doc.setLineWidth(1.2);
  doc.rect(8, 8, pageWidth - 16, 281 - 16);
  doc.setLineWidth(0.3);
  doc.rect(11, 11, pageWidth - 22, 281 - 22);

  // Header banner
  doc.setFillColor(20, 40, 90);
  doc.rect(11, 11, pageWidth - 22, 26, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.text('CSR COMPLIANCE CERTIFICATE', pageWidth / 2, 22, { align: 'center' });

  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.text('SAMAJSEVA — Societal Innovation Collaboration Portal', pageWidth / 2, 29, { align: 'center' });
  doc.text('Government of Jharkhand | Dept. of Higher & Technical Education', pageWidth / 2, 34, { align: 'center' });

  doc.setTextColor(0, 0, 0);

  let y = 50;

  // Certificate meta row
  doc.setFontSize(8.5);
  doc.setFont(undefined, 'italic');
  doc.setTextColor(90, 90, 90);
  doc.text(`Certificate ID: ${funding.id || 'PENDING'}`, margin, y);
  doc.text(`Issued: ${new Date().toLocaleDateString('en-IN')}`, pageWidth - margin, y, { align: 'right' });
  doc.setTextColor(0, 0, 0);

  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Section: Funding Details (structured two-column)
  const sectionTitle = (title) => {
    doc.setFillColor(235, 238, 245);
    doc.rect(margin, y - 5, pageWidth - margin * 2, 8, 'F');
    doc.setFontSize(10.5);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(20, 40, 90);
    doc.text(title, margin + 2, y);
    doc.setTextColor(0, 0, 0);
    y += 12;
  };

  const addRow = (label, value) => {
    doc.setFontSize(9.5);
    doc.setFont(undefined, 'bold');
    doc.text(label, margin + 2, y);
    doc.setFont(undefined, 'normal');
    const lines = doc.splitTextToSize(String(value || 'N/A'), 110);
    doc.text(lines, margin + 55, y);
    y += Math.max(7, lines.length * 5.5);
  };

  sectionTitle('Funding Details');
  addRow('Funding Company:', funding.companyEmail);
  addRow('Amount Funded:', `Rs. ${String(funding.amount || 'N/A').replace(/[₹]/g, '').trim()}`);
  addRow('Implementing Partner:', proposal.uniEmail);
  addRow('Project Category:', issue?.aiCategory || 'N/A');
  addRow('Location:', issue?.location || 'N/A');

  y += 4;
  sectionTitle('Project Overview');

  doc.setFontSize(9.5);
  doc.setFont(undefined, 'bold');
  doc.text('Problem Description:', margin + 2, y);
  y += 6;
  doc.setFont(undefined, 'normal');
  const descLines = doc.splitTextToSize(issue?.description || 'N/A', pageWidth - margin * 2 - 4);
  doc.text(descLines, margin + 2, y);
  y += descLines.length * 5.5 + 8;

  doc.setFont(undefined, 'bold');
  doc.text('Proposed Solution:', margin + 2, y);
  y += 6;
  doc.setFont(undefined, 'normal');
  const solLines = doc.splitTextToSize(proposal.solution || 'N/A', pageWidth - margin * 2 - 4);
  doc.text(solLines, margin + 2, y);
  y += solLines.length * 5.5 + 10;

  // Signature / Seal block
  y = Math.max(y, 235);
  doc.setDrawColor(20, 40, 90);
  doc.line(margin + 2, y, margin + 62, y);
  doc.line(pageWidth - margin - 62, y, pageWidth - margin - 2, y);
  y += 5;
  doc.setFontSize(8.5);
  doc.setFont(undefined, 'normal');
  doc.text('Authorized Signatory (Industry Partner)', margin + 2, y);
  doc.text('Authorized Signatory (University)', pageWidth - margin - 62, y);

  // Footer disclaimer
  y = 262;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 4;
  doc.setFontSize(7.5);
  doc.setTextColor(120, 120, 120);
  doc.text(
    'This certificate is auto-generated by the SAMAJSEVA platform as an official record of CSR fund allocation under the Societal Innovation Collaboration Portal (PS26043).',
    pageWidth / 2, y, { maxWidth: 175, align: 'center' }
  );

  doc.save(`CSR-Certificate-${funding.id || Date.now()}.pdf`);
};